Requiring access
thinknetica-django-lab-01/Zed-chi pull request #47
Opened 2021-02-07 18:59 UTC by Zed-chi

Closes #40

2021-02-08 09:53 UTC, morgangt requested changes

2021-02-08 09:53 UTC, morgangt commented on main/models.py
> +        max_length=500, null=False, blank=False, default="...",
Лучше default а когда в шаблоне надо выводить ... тогда в шаблоне лучше сделать условие {% if not item.description  %}...

2021-02-08 09:53 UTC, morgangt commented on main/views.py
>  def homepage(request):
У вас для отображения страниц везде используются классы CBV а здесь для отображения одной странице функция FBV давайте для отображения главной тоже сделаем класс, для поддержания единообразия

2021-02-08 09:53 UTC, morgangt commented on main/views.py
> +class AddGoodView(CreateView):
Давайте для каждого view класса добавим docstring

2021-02-08 13:34 UTC, Zed-chi commented on main/views.py
> +class AddGoodView(CreateView):
ок

2021-02-09 10:38 UTC, morgangt approved these changes

2021-02-09 16:50 UTC, merged